<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" ignored="0" name="FREE CRM Test" tests="1" failures="1" timestamp="08 Apr 2021 16:08:05 GMT" time="15.481" errors="0">
  <testcase name="feature" time="14.865" classname="MyRunner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [#1 Free CRM customer relationship management software cloud] but found [Free CRM #1 cloud software for any business large or small]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [#1 Free CRM customer relationship management software cloud] but found [Free CRM #1 cloud software for any business large or small]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at MyRunner.TestRunner.feature(TestRunner.java:38)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected [#1 Free CRM customer relationship management software cloud] but found [Free CRM #1 cloud software for any business large or small]
at stepDefinitions.LoginStepDefinition.title_of_login_page_is_free_CRM(LoginStepDefinition.java:34)
at âœ½.When title of login page is Free CRM(login.feature:6)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- FREE CRM Test -->
